# Site settings
title: Ari Blogs
email: hello@ariari.io
description: > # this means to ignore newlines until "baseurl:"
  Ari writes about the things that get her hyped. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ariari.io" # the base hostname & protocol for your site
twitter_username: imariari
github_username:  arirawr

# Build settings
markdown: kramdown


